### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by jjaderg** [mvfsillva/devfestne-17#2]
# Web

![devfest](https://user-images.githubusercontent.com/15023006/29466287-becde4e6-8412-11e7-8039-f1966aec9412.png)
___
# Mobile

![site_devfest_mobile](https://user-images.githubusercontent.com/15023006/30038318-7ba910a2-9199-11e7-8f65-025530e41dfd.jpg)

**Comment by massilva** [comment]
Tem como dividir esta tarefa em partes menores, para permitir o paralelismo :smile: ?

**Comment by jjaderg** [comment]
Sim, você pode acompanhar por (aqui)[https://github.com/mvfsillva/devfestne-17/projects/2]
