### ISSUE TITLE
componente: StatisticBlock

### ISSUE THREAD

**Issue by jjaderg** [mvfsillva/devfestne-17#5]
Elementos:
- [x] 4 blocos.
- [x] Valor numérico para da cada bloco.
- [x] Subtítulo para da bloco usando as cores da paleta do Google.

![blocks](https://user-images.githubusercontent.com/15023006/29594556-25998e64-8788-11e7-9a90-90931bcd0aad.png)

**Comment by felisio** [comment]
Criei o component dentro de Page e chamei de EventInfo... depois cria outro component para representar somente o StaticsBlock
