### ISSUE TITLE
componente: MainHeader

### ISSUE THREAD

**Issue by jjaderg** [mvfsillva/devfestne-17#6]
Elementos:
- [x] Usar Viewport nessa section.
- [x] Ilustração/imagem da cidade de salvador alinhada ao centro.
- [x] **Modificação no layout:** Não usar bordas

![header](https://user-images.githubusercontent.com/15023006/29594846-2f00445a-878a-11e7-9744-b277a97c08a9.png)

**Comment by felisio** [comment]
Vou incluir o Svg-loader para da uma testada no carregamento direto do SVG, caso contrario teríamos que transformar cada SVG em um component VUE

**Comment by felisio** [comment]
O svg-loader não estava setando os estilos corretamente do svg, como não ia perde tempo com isso, criei o component vue com o svg, vamos ter que fazer isso para todos os svgs

**Comment by mvfsillva** [comment]
Time vamos focar em terminar esse card?
